/**
 * Seed data for Firestore
 * Sample destinations and attractions for MVP
 */

import type { Destination, Attraction } from './firestore-schema';

export const seedDestinations: Destination[] = [
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    region: 'Île-de-France',
    latitude: 48.8566,
    longitude: 2.3522,
    description: 'The City of Light, known for art, architecture, and culture',
    population: 2161000,
    attractionCount: 5,
    createdAt: new Date(),
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Kanto',
    latitude: 35.6762,
    longitude: 139.6503,
    description: 'A vibrant metropolis blending ancient tradition with cutting-edge technology',
    population: 13960000,
    attractionCount: 5,
    createdAt: new Date(),
  },
  {
    id: 'new-york',
    name: 'New York City',
    country: 'United States',
    region: 'New York',
    latitude: 40.7128,
    longitude: -74.006,
    description: 'The city that never sleeps, home to iconic landmarks and world-class museums',
    population: 8398748,
    attractionCount: 5,
    createdAt: new Date(),
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    region: 'Catalonia',
    latitude: 41.3851,
    longitude: 2.1734,
    description: 'Catalan capital famous for modernist architecture and Mediterranean beaches',
    population: 1620343,
    attractionCount: 5,
    createdAt: new Date(),
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Bali',
    latitude: -8.6705,
    longitude: 115.2126,
    description: 'A tropical paradise known for beaches, temples, and lush rice terraces',
    population: 3890757,
    attractionCount: 5,
    createdAt: new Date(),
  },
];

export const seedAttractions: Attraction[] = [
  {
    id: 'paris-eiffel-tower',
    destinationId: 'paris',
    name: 'Eiffel Tower',
    description: 'Iconic iron lattice monument offering panoramic views of Paris',
    category: 'monument',
    budgetLevel: 'moderate',
    tags: ['cultural', 'historical', 'iconic', 'photography'],
    latitude: 48.8584,
    longitude: 2.2945,
    rating: 4.7,
    reviewCount: 89540,
    website: 'https://www.toureiffel.paris/',
    source: 'seeded',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'paris-louvre',
    destinationId: 'paris',
    name: 'Louvre Museum',
    description: 'Worlds largest art museum with the famous Mona Lisa',
    category: 'museum',
    budgetLevel: 'moderate',
    tags: ['art', 'cultural', 'indoor', 'historical'],
    latitude: 48.861,
    longitude: 2.3359,
    rating: 4.6,
    reviewCount: 67203,
    website: 'https://www.louvre.fr/',
    source: 'seeded',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tokyo-senso-ji',
    destinationId: 'tokyo',
    name: 'Senso-ji Temple',
    description: 'Ancient Buddhist temple and popular tourist destination',
    category: 'temple',
    budgetLevel: 'budget',
    tags: ['religious', 'historical', 'cultural', 'photography'],
    latitude: 35.7148,
    longitude: 139.7967,
    rating: 4.6,
    reviewCount: 58760,
    source: 'seeded',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'nyc-statue-of-liberty',
    destinationId: 'new-york',
    name: 'Statue of Liberty',
    description: 'Iconic symbol of freedom and democracy on Liberty Island',
    category: 'monument',
    budgetLevel: 'moderate',
    tags: ['historical', 'iconic', 'photography', 'cultural'],
    latitude: 40.6892,
    longitude: -74.0445,
    rating: 4.5,
    reviewCount: 52340,
    source: 'seeded',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'barcelona-sagrada-familia',
    destinationId: 'barcelona',
    name: 'Sagrada Familia',
    description: 'Gaudis unfinished masterpiece basilica with distinctive architecture',
    category: 'monument',
    budgetLevel: 'moderate',
    tags: ['architecture', 'historical', 'cultural', 'iconic'],
    latitude: 41.4036,
    longitude: 2.1744,
    rating: 4.7,
    reviewCount: 76250,
    source: 'seeded',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'bali-rice-terraces',
    destinationId: 'bali',
    name: 'Rice Terraces',
    description: 'Lush green rice paddies offering scenic landscape views',
    category: 'nature',
    budgetLevel: 'budget',
    tags: ['outdoor', 'photography', 'nature', 'peaceful'],
    latitude: -8.4298,
    longitude: 115.2625,
    rating: 4.7,
    reviewCount: 41250,
    source: 'seeded',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
